package irepository

import (
	"context"

	"github.com/ecocomply/auth-service/internal/domain"
	"github.com/google/uuid"
)

// UserRepository defines all data access operations for users.
// The postgres implementation lives in repository/postgres/user_repo.go.
// The mock lives in mocks/ and is generated by mockery.
type UserRepository interface {
	Create(ctx context.Context, user *domain.User) error
	FindByID(ctx context.Context, id uuid.UUID) (*domain.User, error)
	FindByEmail(ctx context.Context, email string) (*domain.User, error)
	Update(ctx context.Context, user *domain.User) error
	SoftDelete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, limit, offset int) ([]domain.User, int64, error)
}
